export const userDashboardData = [
  { title: "Total User ", data: "140", style: "text-[#434444]" },
  { title: "Total Orders ", data: "118", style: "text-[#FDC63A]" },
  { title: "Orders Pending ", data: "140", style: "text-[#D31010]" },
  { title: "Orders Completed ", data: "118", style: "text-[#0FB001]" },
];
export const ordersTabledata = [
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Pending",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Kiran Kumar",
    location: "JP Nagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Pending",
  },
  {
    date: "",
    id: "",
    user: "",
    location: "",
    referral: "",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "",
    status: "",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Mallika",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Dispatched",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Amith gupta",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Dispatched",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Cancelled",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Delivered",
  },
];
export const ordersLogsdata = [
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    vender: "Rajesh",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    person: "Frediks",
    status: "Cancelled",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Kiran Kumar",
    location: "JP Nagar",
    referral: "Mahima(MM3456)",
    items: "LED Bulbs, Stylish Tiles ",
    vender: "Kamal",
    qty: "05",
    price: "₹563",
    paymentMode: "COD",
    person: "Ramu",
    status: "Cancelled",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Nallitha Hari",
    location: "Ramnagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    vender: "Champak",
    qty: "01",
    price: "₹563",
    paymentMode: "Online",
    person: "Ramu",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Keerthi Jain",
    location: "RR Nagar",
    referral: "-",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "03",
    price: "₹563",
    paymentMode: "Online",
    person: "Kiran",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Mallika",
    location: "Jayanagar",
    referral: "-",
    items: "LED Bulbs ",
    vender: "Ramu set",
    qty: "03",
    price: "₹563",
    paymentMode: "Online",
    person: "Ramu",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Amith gupta",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "LED Bulbs ",
    vender: "KRK Paan",
    qty: "03",
    price: "₹563",
    paymentMode: "COD",
    person: "Kiran",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    vender: "Suguresh",
    qty: "01",
    price: "₹563",
    paymentMode: "Online",
    person: "Frediks",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "05",
    price: "₹563",
    paymentMode: "COD",
    person: "Veeraat",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "05",
    price: "₹563",
    paymentMode: "COD",
    person: "Chiyaan",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "05",
    price: "₹563",
    paymentMode: "Online",
    person: "Morgan",
    status: "Delivered",
  },
];
