export const userDashboardData = [
  { title: "Total User ", data: "140", style: "text-[#434444]" },
  { title: "Total Orders ", data: "118", style: "text-[#FDC63A]" },
  { title: "Orders Pending ", data: "140", style: "text-[#D31010]" },
  { title: "Orders Completed ", data: "118", style: "text-[#0FB001]" },
];
export const ordersTabledata = [
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Pending",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Kiran Kumar",
    location: "JP Nagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Pending",
  },
  {
    date: "",
    id: "",
    user: "",
    location: "",
    referral: "",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "",
    status: "",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Mallika",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Dispatched",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Amith gupta",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Dispatched",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Cancelled",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "COD",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    status: "Delivered",
  },
];
export const ordersLogsdata = [
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    vender: "Rajesh",
    qty: "100",
    price: "₹17630",
    paymentMode: "Online",
    person: "Frediks",
    status: "Cancelled",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Kiran Kumar",
    location: "JP Nagar",
    referral: "Mahima(MM3456)",
    items: "LED Bulbs, Stylish Tiles ",
    vender: "Kamal",
    qty: "05",
    price: "₹563",
    paymentMode: "COD",
    person: "Ramu",
    status: "Cancelled",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Nallitha Hari",
    location: "Ramnagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    vender: "Champak",
    qty: "01",
    price: "₹563",
    paymentMode: "Online",
    person: "Ramu",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Keerthi Jain",
    location: "RR Nagar",
    referral: "-",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "03",
    price: "₹563",
    paymentMode: "Online",
    person: "Kiran",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Mallika",
    location: "Jayanagar",
    referral: "-",
    items: "LED Bulbs ",
    vender: "Ramu set",
    qty: "03",
    price: "₹563",
    paymentMode: "Online",
    person: "Ramu",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Amith gupta",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "LED Bulbs ",
    vender: "KRK Paan",
    qty: "03",
    price: "₹563",
    paymentMode: "COD",
    person: "Kiran",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Mahima(MM3456)",
    items: "Stylish Tiles ",
    vender: "Suguresh",
    qty: "01",
    price: "₹563",
    paymentMode: "Online",
    person: "Frediks",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "Kiran(KD2458)",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "05",
    price: "₹563",
    paymentMode: "COD",
    person: "Veeraat",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "05",
    price: "₹563",
    paymentMode: "COD",
    person: "Chiyaan",
    status: "Delivered",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    user: "Rajesh",
    location: "Jayanagar",
    referral: "-",
    items: "Stylish Tiles ",
    vender: "Mahesh",
    qty: "05",
    price: "₹563",
    paymentMode: "Online",
    person: "Morgan",
    status: "Delivered",
  },
];
export const userData = [
  {
    date: "26/02/23",
    user: "Kiran",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Jayanagar",
    referral: "12",
    status: "Active",
  },
  {
    date: "26/02/23",
    user: "Mahesh",
    mobile: "8474747494",
    email: "rajdjd@gmail.com",
    location: "Hebbal",
    referral: "06",
    status: "Active",
  },
  {
    date: "26/02/23",
    user: "Tippuu",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Kanakpura",
    referral: "09",
    status: "Active",
  },
  {
    date: "26/02/23",
    user: "Amith Jain",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "JP nagar",
    referral: "14",
    status: "Active",
  },
  {
    date: "26/02/23",
    user: "Tippuraj",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "RR Nagar",
    referral: "02",
    status: "Active",
  },
  {
    date: "26/02/23",
    user: "Kapil Sharma",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Bidar",
    referral: "06",
    status: "Inactive",
  },
  {
    date: "26/02/23",
    user: "Madhan",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Mumbai",
    referral: "02",
    status: "Active",
  },
  {
    date: "26/02/23",
    user: "Rekha",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Delhi",
    referral: "06",
    status: "Active",
  },
  {
    date: "26/02/23",
    user: "Sushmitha",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Kalburgi",
    referral: "02",
    status: "Inactive",
  },
  {
    date: "26/02/23",
    user: "Rajesh",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Thaane",
    referral: "06",
    status: "Inactive",
  },
  {
    date: "26/02/23",
    user: "Rajesh",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Madhirai",
    referral: "02",
    status: "Pending",
  },
  {
    date: "26/02/23",
    user: "Rajesh",
    mobile: "8474747494",
    email: "rajeh@gmail.com",
    location: "Wash & Iron",
    referral: "06",
    status: "Pending",
  },
];
export const referralData = [
  {
    date: "26/02/23",
    user: "Rajesh",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Primary",
  },
  {
    date: "26/02/23",
    user: "Mathesh",
    mobile: "8474747494",
    location: "Hebbal",
    referral: "Primary",
  },
  {
    date: "26/02/23",
    user: "Kiran",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Primary",
  },
  {
    date: "26/02/23",
    user: "Amith Jain",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Tippuraj",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Kapil Sharma",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Madhan",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Rekha",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Sushmitha",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Rajesh",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Rajesh",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
  {
    date: "26/02/23",
    user: "Rajesh",
    mobile: "8474747494",
    location: "Jayanagar",
    referral: "Secondary",
  },
];
export const userOrderData = [
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Stylish Tiles ",
    amount: "₹ 4589",
    payment: "Online",
    status: "Paid",
  },
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Stylish Tiles ",
    amount: "₹ 4589",
    payment: "Online",
    status: "Paid",
  },
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Stylish Tiles ",
    amount: "₹ 4589",
    payment: "COD",
    status: "Paid",
  },
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Stylish Tiles ",
    amount: "₹ 4589",
    payment: "COD",
    status: "Paid",
  },
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Stylish Tiles ",
    amount: "₹ 4589",
    payment: "Online",
    status: "Paid",
  },
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Stylish Tiles ",
    amount: "₹ 4589",
    payment: "Online",
    status: "Paid",
  },
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Madhan ",
    amount: "8474747494",
    payment: "COD",
    status: "Paid",
  },
  {
    date: "26/02/23",
    id: "#2385485",
    items: "Rekha ",
    amount: "8474747494",
    payment: "COD",
    status: "Paid",
  },
];
import tiles from "../../assets/images/png/tiles.png";
import taps from "../../assets/images/png/taps.png";
export const categoriesData = [
  {
    date: "26/02/23",
    img: tiles,
    category: "Tiles",
    products: "22",
    orders: "00",
  },
  {
    date: "26/02/23",
    img: taps,
    category: "Taps",
    products: "33",
    orders: "00",
  },
  {
    date: "26/02/23",
    img: tiles,
    category: "Tiles",
    products: "22",
    orders: "12",
  },
  {
    date: "26/02/23",
    img: taps,
    category: "Taps",
    products: "33",
    orders: "06",
  },
  {
    date: "26/02/23",
    img: tiles,
    category: "Tiles",
    products: "22",
    orders: "12",
  },
  {
    date: "26/02/23",
    img: taps,
    category: "Taps",
    products: "33",
    orders: "06",
  },
  {
    date: "26/02/23",
    img: tiles,
    category: "Tiles",
    products: "22",
    orders: "12",
  },
  {
    date: "26/02/23",
    img: taps,
    category: "Taps",
    products: "33",
    orders: "06",
  },
];
export const productDetailsData = [
  {
    date: "26/02/23",
    product: "Italian",
    price: "12",
    orders: "12",
  },
  {
    date: "26/02/23",
    product: "Italian",
    price: "06",
    orders: "06",
  },
  {
    date: "26/02/23",
    product: "Italian",
    price: "12",
    orders: "12",
  },
  {
    date: "26/02/23",
    product: "Italian",
    price: "06",
    orders: "06",
  },
  {
    date: "26/02/23",
    product: "Italian",
    price: "12",
    orders: "12",
  },
  {
    date: "26/02/23",
    product: "Italian",
    price: "06",
    orders: "06",
  },
  {
    date: "26/02/23",
    product: "Italian",
    price: "12",
    orders: "12",
  },
  {
    date: "26/02/23",
    product: "Italian",
    price: "06",
    orders: "06",
  },
];
export const complaintsTableData = [
  {
    date: "26/02/23",
    id: "#3537379",
    customer: "Rajesh",
    mobile: "8474747494",
    items: "Stylish tiles",
    complaints: "",
    status: "Resolved",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    customer: "Rajesh",
    mobile: "8474747494",
    items: "LED Bulbs",
    complaints: "",
    status: "Resolved",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    customer: "Rajesh",
    mobile: "8474747494",
    items: "Stylish tiles",
    complaints: "",
    status: "Resolved",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    customer: "Rajesh",
    mobile: "8474747494",
    items: "Stylish tiles",
    complaints: "",
    status: "Pending",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    customer: "Rajesh",
    mobile: "8474747494",
    items: "LED Bulbs",
    complaints: "",
    status: "Pending",
  },
  {
    date: "26/02/23",
    id: "#3537379",
    customer: "Rajesh",
    mobile: "8474747494",
    items: "LED Bulbs",
    complaints: "",
    status: "Pending",
  },
];
